name: ushap_raster2polygon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - gdal=3.8.4
  - netcdf4=1.6.5
  - xarray=2023.12.0
  - rasterio=1.3.9
  - rasterstats=0.19.0
  - geopandas=0.14.2
  - pyarrow=14.0.2
  - pip=23.3.2
  - pip:
    - requests==2.31.0
    - wget==3.2
    - hydra-core==1.3.2
    - snakemake==8.1.2
    - tqdm==4.66.2
