defaults:
  - _self_
  - datapaths: local
  - ushap
  - shapefiles: us_census

# == aggregation args
temporal_freq: monthly  # daily, monthly, yearly
year: 2002

# == shapefile download args
polygon_name: county   # zcta, county
shapefile_year: 2000

plot_output: true  # plots the first day of each var aggregation for debugging

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}

    