defaults:
  - _self_
  - datapaths: bronx
  - ushap
  - shapefiles: bronx

# == aggregation args
temporal_freq: monthly  # daily, monthly, yearly
year: 2020

# == shapefile download args
polygon_name: bronx   # zcta, county
shapefile_year: 2021

plot_output: true  # plots the first day of each var aggregation for debugging

hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
