# if files are stored within the local copy of the repository, then use null:
input:
  ushap:
    daily: null
    monthly: null
    yearly: null
  shapefiles: null

intermediate:
  pkl_shapefiles: null

output:
  ushap_raster2polygon: 
    daily: null
    monthly: null
    yearly: null
